events {
worker_connections 1024;
}

http {
server {
listen 80;
server_name skydishch.fun;

# Set max body size and proxy timeouts
client_max_body_size 10000M;
proxy_connect_timeout 1800s;
proxy_send_timeout 1800s;
proxy_read_timeout 1800s;

# React App and static files
root /usr/share/nginx/html;
index index.html;

# Route API traffic to NestJS backend
location /api/ {
    proxy_pass http://backend:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

# Route emulator traffic to emulator service
location /emulator/ {
    proxy_pass http://emulator:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

# Route roms traffic to romserv service
location /roms/ {
    proxy_pass http://romserv:9999/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

# Serve static assets with caching headers
location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|otf)$ {
    expires 1y;
    access_log off;
    add_header Cache-Control "public";
    add_header Access-Control-Allow-Origin *;
}

# React App's routing for single-page application
location / {
    try_files $uri $uri/ /index.html;
}

}
}