export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  user: '/user',
  admin: '/admin',
  about: '/about',
  services: '/services',
  portfolio: '/portfolio',
  whyus: '/whyus',
  skills: '/skills',
  testimonials: '/testimonials',
  contact: '/contact',
  faq: '/faq',
};