version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: Database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: xsanderadmin
      POSTGRES_PASSWORD: qweasdrtyfghvbnjklyuiospgmrj
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./NestJS
    container_name: backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: xsanderadmin
      DB_PASSWORD: qweasdrtyfghvbnjklyuiospgmrj
      DB_DATABASE: postgres
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./NestJS/uploads:/app/uploads
      - ./NestJS/storage:/app/storage
      - ./NestJS/CloudFile:/app/CloudFile

  emulator:
    build: ./EmulatorServ
    container_name: emulator
    ports:
      - "8080:8080"
    networks:
      - app-network

  romserv:
    build: ./RomServ
    container_name: romserv
    ports:
      - "9999:9999"
    volumes:
      - ./RomServ/Games:/app/Games
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
