version: '3.8'

services:
  nginx:
    # Build the image using the Dockerfile in the client directory.
    # This will handle the build of the React app and serving it with Nginx.
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount the Let's Encrypt certificates.
      - certbot-webroot:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - backend
      - emulator
      - romserv
    restart: always

  postgres:
    image: postgres:15
    container_name: Database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: xsanderadmin
      POSTGRES_PASSWORD: qweasdrtyfghvbnjklyuiospgmrj
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./NestJS
    container_name: backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: xsanderadmin
      DB_PASSWORD: qweasdrtyfghvbnjklyuiospgmrj
      DB_DATABASE: postgres
      JWT_SECRET: your_super_secret_key
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./NestJS/uploads:/app/uploads
      - ./NestJS/storage:/app/storage
      - ./NestJS/CloudFile:/app/CloudFile
  
  romserv:
    build: ./RomServ
    container_name: romserv
    ports:
      - "9999:9999"
    volumes:
      - ./RomServ/Games:/app/Games
    networks:
      - app-network
    depends_on:
      - backend

  emulator:
    build: ./EmulatorServ
    container_name: emulator
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - romserv
  
  # Certbot service for automated certificate renewal
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-webroot:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --force-renewal -d skydishch.fun --email your-email@example.com --agree-tos --no-eff-email
    restart: unless-stopped
    networks:
      - app-network

volumes:
  certbot-webroot:
  certbot-certs:

networks:
  app-network:
    driver: bridge
