version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ServerAPI
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://xsanderadmin:qazxdr5WSE#!QAZXDR%2wse43@postgres:5432/mydatabase
      - DEBUG=True
    volumes:
      - ./server:/app
    depends_on:
      - postgres
    networks:
      - app-network
    restart: always 

  postgres:
    image: postgres:15
    container_name: Database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: xsanderadmin
      POSTGRES_PASSWORD: qazxdr5WSE#!QAZXDR%2wse43
      POSTGRES_DB: mydatabase
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always 

networks:
  app-network:
    driver: bridge