export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  user: '/user',
  admin: '/admin',
  about: '/about',
  news: '/news',
  portfolio: '/portfolio',
  whyus: '/whyus',
  skills: '/skills',
  blog: '/blog',
  filecloud: '/filecloud',
  faq: '/faq',
  notFound: '*',
};