server {
listen 80;
listen [::]:80;
server_name skydishch.fun www.skydishch.fun;

client_max_body_size 10000M;

location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot/; 
}

location / {
    return 301 https://$host$request_uri;
}

}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name skydishch.fun www.skydishch.fun 78.26.216.97;

client_max_body_size 10000M;

ssl_certificate /etc/letsencrypt/live/skydishch.fun/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/skydishch.fun/privkey.pem;
ssl_trusted_certificate /etc/letsencrypt/live/skydishch.fun/chain.pem;

ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;

root /home/zmxncbv/www/Rest_Api_ToDo/client/build; 
index index.html;

location /api/ {
    proxy_pass http://localhost:5000/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 1800s;
    proxy_send_timeout 1800s;
    proxy_read_timeout 1800s;
}

location /roms/ {
    rewrite ^/roms/?(.*)$ /$1 break;
    proxy_pass http://localhost:9999/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /emulator/ {
    proxy_pass http://localhost:8080/; 
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|otf)$ {
    expires 1y;
    access_log off;
    add_header Cache-Control "public";
    add_header Access-Control-Allow-Origin *;
}

location = /favicon.ico {
    access_log off;
    log_not_found off;
}

location = /robots.txt {
    access_log off;
    log_not_found off;
}

location / {
    try_files $uri /index.html;
}

}